# Generated by Django 5.0.7 on 2025-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('comments_id', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('time_published', models.DateTimeField(auto_now_add=True)),
                ('difficult', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('bookmarks_count', models.IntegerField(default=0)),
            ],
        ),
    ]
