# Generated by Django 5.0.7 on 2025-04-05 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Describe yourself')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Specialty')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='N', max_length=1, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Age')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='users_profile.additionaluserinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_link', models.URLField(blank=True, null=True, verbose_name='Google link')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub link')),
                ('head_hunter_link', models.URLField(blank=True, null=True, verbose_name='HeadHunter link')),
                ('habr_link', models.URLField(blank=True, null=True, verbose_name='Habr link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users_profile.additionaluserinfo')),
            ],
        ),
    ]
